### ISSUE TITLE
dart bridge fails after building with `new bridge my_blog`

### ISSUE THREAD

**Issue by kasperpeulen** [dart-bridge/dart-bridge.github.io#2]
In the documentation, it says:

> Starting up Bridge is super simple:
> 
> $ dart bridge

But when doing that I got this error:

```
dart bridge
Initialization failed.
ConfigException: No MongoDB server is running on port 27017. Check your configuration or remove [bridge.database.DatabaseServiceProvder] from your service provider list.
```

When I removed `bridge.database.DatabaseServiceProvder` from `comfig/app.yaml`, everything worked fine. Btw I builded the app with:

`$ new_bridge my_blog`

**Comment by emilniklas** [comment]
This is as it should be. The bridge boilerplate app uses the database component, which expects a mongo server to be running.

This really gives a bad first impression, so I think I'll remove the database component from the default set of compoments

**Comment by kasperpeulen** [comment]
Or maybe something in the documentation that there will be an error ? Or maybe an tutorial how to set up mongo db with bridge ?

**Comment by emilniklas** [comment]
All good ideas!
I think a mention of a tutorial in the documentation hos to set up a database, plus removing the database service as a default will do the trick

**Comment by emilniklas** [comment]
As of Alpha 4 the app starts out using an in memory database
