### ISSUE TITLE
instructions in "Returning a template" failed

### ISSUE THREAD

**Issue by SatWiz** [dart-bridge/dart-bridge.github.io#3]
Hello, followed the instructions in the quick tour to learn more from the framework.
But it seems return template('index') will cause an internal server error:
Error in HTTP layer:
Class 'Api' has no instance method 'template'.

NoSuchMethodError: method not found: 'template'
Receiver: Instance of 'Api'
Arguments: ["index"]

**Comment by emilniklas** [comment]
Yes, that's because the template helper function is located in the library `bridge.view`.

```
import 'package:bridge/view.dart';
```

Add that to the top of `api.dart` and you'll be fine. If you're using the IntelliJ plugin, you should be able to Alt+Enter and import automatically.
